#!/usr/bin/env python3
"""
NPV/NPVT Converter - Convert VLESS/VMess config to NPV file format
https://github.com/yourusername/g2ray

Usage:
    python3 npvt_converter.py --vless "vless://UUID@server:port?params#remarks"
    python3 npvt_converter.py --json config.json
    python3 npvt_converter.py --uuid UUID --server SERVER --port PORT --sni SNI
"""

import base64
import json
import argparse
import urllib.parse
import re
import sys
from typing import Optional, Dict, Any


def parse_vless_url(url: str) -> Dict[str, Any]:
    """Parse VLESS URL into configuration dict"""
    # Remove vless:// prefix
    if url.startswith('vless://'):
        url = url[7:]
    
    # Split at # for remarks
    remarks = ""
    if '#' in url:
        url, remarks = url.split('#', 1)
        remarks = urllib.parse.unquote(remarks)
    
    # Split server:port from query params
    if '?' in url:
        server_part, query = url.split('?', 1)
        params = urllib.parse.parse_qs(query, keep_blank_values=True)
        params = {k: v[0] for k, v in params.items()}
    else:
        server_part = url
        params = {}
    
    # Parse server:port
    if '@' in server_part:
        uuid, server = server_part.split('@', 1)
    else:
        uuid = ""
        server = server_part
    
    # Parse port
    port = 443
    if ':' in server:
        server, port_str = server.rsplit(':', 1)
        port = int(port_str)
    
    config = {
        "uuid": uuid,
        "server": server,
        "port": port,
        "encryption": params.get("encryption", "none"),
        "transport": params.get("type", "ws"),
        "path": params.get("path", "/"),
        "tls": params.get("security", "tls") == "tls",
        "sni": params.get("sni", server),
        "remarks": remarks or "g2ray"
    }
    
    return config


def config_to_npv(config: Dict[str, Any], hardware_id: Optional[str] = None) -> str:
    """Convert config dict to NPV format"""
    
    # NPV format structure (based on research)
    npv_config = {
        "protocol": config.get("protocol", "vless").upper(),
        "server": config["server"],
        "port": config["port"],
        "uuid": config["uuid"],
        "encryption": config.get("encryption", "none"),
        "transport": config.get("transport", "ws"),
        "path": config.get("path", "/"),
        "tls": config.get("tls", True),
        "sni": config.get("sni", config["server"]),
        "remarks": config.get("remarks", "g2ray")
    }
    
    # Add hardware binding if provided (for locking)
    if hardware_id:
        npv_config["hardware_id"] = hardware_id
        npv_config["locked"] = True
    
    # Convert to JSON then base64 encode
    json_str = json.dumps(npv_config, indent=2)
    b64_encoded = base64.b64encode(json_str.encode('utf-8')).decode('utf-8')
    
    # NPV format: header + base64 + footer
    npv_content = f"""# NPV Config - Generated by g2ray
# Date: 2024
# Protocol: VLESS
-----BEGIN NPV CONFIG-----
{b64_encoded}
-----END NPV CONFIG-----
"""
    
    return npv_content


def config_to_npvt(config: Dict[str, Any]) -> str:
    """Convert config to NPVT format - trying various formats"""
    
    # Build config
    npvt_config = {
        "server": config["server"],
        "port": config["port"],
        "uuid": config["uuid"],
        "encryption": config.get("encryption", "none"),
        "transport": config.get("transport", "ws"),
        "path": config.get("path", "/"),
        "tls": config.get("tls", True),
        "sni": config.get("sni", config["server"]),
        "remarks": config.get("remarks", "g2ray")
    }
    
    json_str = json.dumps(npvt_config)
    b64_str = base64.b64encode(json_str.encode()).decode()
    
    # Return with NPV signature
    return "NPV1" + b64_str


def generate_npv_file(vless_url: str = None, json_file: str = None, 
                   uuid: str = None, server: str = None, port: int = 443,
                   sni: str = None, output: str = "config.npv",
                   npvt: bool = False) -> str:
    """Generate NPV/NPVT file from inputs"""
    
    # Get config from URL
    if vless_url:
        config = parse_vless_url(vless_url)
    elif json_file:
        with open(json_file, 'r') as f:
            config = json.load(f)
    elif uuid and server:
        config = {
            "protocol": "VLESS",
            "uuid": uuid,
            "server": server,
            "port": port,
            "sni": sni or server,
            "transport": "ws",
            "path": "/",
            "tls": True,
            "encryption": "none",
            "remarks": "g2ray"
        }
    else:
        raise ValueError("Please provide either --vless, --json, or --uuid/--server")
    
    # Generate file content
    if npvt:
        content = config_to_npvt(config)
    else:
        content = config_to_npv(config)
    
    # Write to file
    with open(output, 'w') as f:
        f.write(content)
    
    print(f"✅ Generated: {output}")
    if npvt:
        print("📝 Format: NPVT (Base64 encoded)")
    else:
        print("📝 Format: NPV (Base64 encoded with header)")
    
    return output


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Convert VLESS config to NPV/NPVT file format"
    )
    parser.add_argument("--vless", help="Full VLESS URL")
    parser.add_argument("--text", "--remarks", dest="remarks", help="Custom text/remarks for the config")
    parser.add_argument("--json", help="Input JSON config file")
    parser.add_argument("--uuid", help="VLESS UUID")
    parser.add_argument("--server", help="Server IP/hostname")
    parser.add_argument("--port", type=int, default=443, help="Server port")
    parser.add_argument("--sni", help="SNI hostname")
    parser.add_argument("--output", default="config.npv", help="Output file")
    parser.add_argument("--npvt", action="store_true", help="Generate .npvt format")
    parser.add_argument("--hardware-id", help="Hardware ID for locking")
    
    args = parser.parse_args()
    
    try:
        custom_remarks = args.remarks
        generate_npv_file(
            vless_url=args.vless,
            json_file=args.json,
            uuid=args.uuid,
            server=args.server,
            port=args.port,
            sni=args.sni,
            output=args.output,
            npvt=args.npvt
        )
        
        # Add custom text if provided
        if custom_remarks:
            try:
                # Read the file
                with open(args.output or "config.npv", 'r') as f:
                    content = f.read()
                
                # For NPV1 format: NPV1{base64}
                if content.startswith('NPV1'):
                    b64_data = content[4:].strip()
                    # Decode safely
                    try:
                        decoded = json.loads(base64.b64decode(b64_data).decode('utf-8'))
                    except:
                        # Try URL-safe base64
                        import base64
                        decoded = json.loads(base64.urlsafe_b64decode(b64_data + '==').decode('utf-8'))
                    
                    decoded['remarks'] = custom_remarks
                    
                    # Re-encode
                    encoded = base64.b64encode(json.dumps(decoded).encode('utf-8')).decode('utf-8')
                    new_content = "NPV1" + encoded
                    
                    with open(args.output or "config.npv", 'w') as f:
                        f.write(new_content)
                    print(f"✅ Custom text: {custom_remarks}")
            except Exception as e:
                print(f"Note: Could not add text ({e})")
                
    except Exception as e:
        print(f"❌ Error: {e}")
        sys.exit(1)