#!/usr/bin/env python3
"""
NPV/NPVT Converter - Convert VLESS/VMess config to NPV file format
https://github.com/yourusername/g2ray

Usage:
    python3 npvt_converter.py --vless "vless://UUID@server:port?params#remarks"
    python3 npvt_converter.py --json config.json
    python3 npvt_converter.py --uuid UUID --server SERVER --port PORT --sni SNI
"""

import base64
import json
import argparse
import urllib.parse
import re
import sys
from typing import Optional, Dict, Any


def parse_vless_url(url: str) -> Dict[str, Any]:
    """Parse VLESS URL into configuration dict"""
    # Remove vless:// prefix
    if url.startswith('vless://'):
        url = url[7:]
    
    # Split at # for remarks
    remarks = ""
    if '#' in url:
        url, remarks = url.split('#', 1)
        remarks = urllib.parse.unquote(remarks)
    
    # Split server:port from query params
    if '?' in url:
        server_part, query = url.split('?', 1)
        params = urllib.parse.parse_qs(query, keep_blank_values=True)
        params = {k: v[0] for k, v in params.items()}
    else:
        server_part = url
        params = {}
    
    # Parse server:port
    if '@' in server_part:
        uuid, server = server_part.split('@', 1)
    else:
        uuid = ""
        server = server_part
    
    # Parse port
    port = 443
    if ':' in server:
        server, port_str = server.rsplit(':', 1)
        port = int(port_str)
    
    config = {
        "uuid": uuid,
        "server": server,
        "port": port,
        "encryption": params.get("encryption", "none"),
        "transport": params.get("type", "ws"),
        "path": params.get("path", "/"),
        "tls": params.get("security", "tls") == "tls",
        "sni": params.get("sni", server),
        "remarks": remarks or "g2ray"
    }
    
    return config


def config_to_npv(config: Dict[str, Any], hardware_id: Optional[str] = None) -> str:
    """Convert config dict to NPV format"""
    
    # NPV format structure (based on research)
    npv_config = {
        "protocol": config.get("protocol", "vless").upper(),
        "server": config["server"],
        "port": config["port"],
        "uuid": config["uuid"],
        "encryption": config.get("encryption", "none"),
        "transport": config.get("transport", "ws"),
        "path": config.get("path", "/"),
        "tls": config.get("tls", True),
        "sni": config.get("sni", config["server"]),
        "remarks": config.get("remarks", "g2ray")
    }
    
    # Add hardware binding if provided (for locking)
    if hardware_id:
        npv_config["hardware_id"] = hardware_id
        npv_config["locked"] = True
    
    # Convert to JSON then base64 encode
    json_str = json.dumps(npv_config, indent=2)
    b64_encoded = base64.b64encode(json_str.encode('utf-8')).decode('utf-8')
    
    # NPV format: header + base64 + footer
    npv_content = f"""# NPV Config - Generated by g2ray
# Date: 2024
# Protocol: VLESS
-----BEGIN NPV CONFIG-----
{b64_encoded}
-----END NPV CONFIG-----
"""
    
    return npv_content


def config_to_npvt(config: Dict[str, Any]) -> str:
    """Convert config to NPVT format - try different formats"""
    
    # Format 1: Raw vless URL
    vless_url = f"vless://{config['uuid']}@{config['server']}:{config['port']}?encryption={config.get('encryption', 'none')}&security=tls&type={config.get('transport', 'ws')}&sni={config.get('sni', config['server'])}&path={config.get('path', '/')}"
    if config.get('remarks'):
        vless_url += f"#{config['remarks']}"
    
    return vless_url


def generate_npv_file(vless_url: str = None, json_file: str = None, 
                   uuid: str = None, server: str = None, port: int = 443,
                   sni: str = None, output: str = "config.npv",
                   npvt: bool = False) -> str:
    """Generate NPV/NPVT file from inputs"""
    
    # Get config from URL
    if vless_url:
        config = parse_vless_url(vless_url)
    elif json_file:
        with open(json_file, 'r') as f:
            config = json.load(f)
    elif uuid and server:
        config = {
            "protocol": "VLESS",
            "uuid": uuid,
            "server": server,
            "port": port,
            "sni": sni or server,
            "transport": "ws",
            "path": "/",
            "tls": True,
            "encryption": "none",
            "remarks": "g2ray"
        }
    else:
        raise ValueError("Please provide either --vless, --json, or --uuid/--server")
    
    # Generate file content
    if npvt:
        content = config_to_npvt(config)
    else:
        content = config_to_npv(config)
    
    # Write to file
    with open(output, 'w') as f:
        f.write(content)
    
    print(f"✅ Generated: {output}")
    if npvt:
        print("📝 Format: NPVT (Base64 encoded)")
    else:
        print("📝 Format: NPV (Base64 encoded with header)")
    
    return output


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Convert VLESS config to NPV/NPVT file format"
    )
    parser.add_argument("--vless", help="Full VLESS URL")
    parser.add_argument("--text", help="Custom text/remarks")
    parser.add_argument("--json", help="Input JSON config file")
    parser.add_argument("--uuid", help="VLESS UUID")
    parser.add_argument("--server", help="Server IP/hostname")
    parser.add_argument("--port", type=int, default=443, help="Server port")
    parser.add_argument("--sni", help="SNI hostname")
    parser.add_argument("--output", default="config.npv", help="Output file")
    parser.add_argument("--npvt", action="store_true", help="Generate .npvt format")
    parser.add_argument("--all", action="store_true", help="Generate all formats")
    parser.add_argument("--hardware-id", help="Hardware ID for locking")
    
    args = parser.parse_args()
    
    try:
        custom_remarks = args.text
        generate_npv_file(
            vless_url=args.vless,
            json_file=args.json,
            uuid=args.uuid,
            server=args.server,
            port=args.port,
            sni=args.sni,
            output=args.output,
            npvt=args.npvt
        )
        
        # Generate ALL formats for testing
        if args.all:
            # Parse from VLESS URL if provided
            if args.vless:
                config = parse_vless_url(args.vless)
                args.uuid = config.get('uuid')
                args.server = config.get('server')
                args.sni = config.get('sni')
            
            import os
            base, ext = os.path.splitext(args.output)
            
            # Format 1: VLESS URL
            with open(f"{base}_vless.txt", 'w') as f:
                url = f"vless://{args.uuid}@{args.server}:{args.port}?encryption=none&security=tls&type=ws&sni={args.sni}&path=%2F#{custom_remarks or 'remarks'}"
                f.write(url)
            print(f"✅ Generated: {base}_vless.txt")
            
            # Format 2: JSON
            import json
            with open(f"{base}_json.json", 'w') as f:
                json.dump({
                    "server": args.server,
                    "port": args.port,
                    "uuid": args.uuid,
                    "encryption": "none",
                    "transport": "ws",
                    "path": "/",
                    "tls": True,
                    "sni": args.sni,
                    "remarks": custom_remarks or "g2ray"
                }, f, indent=2)
            print(f"✅ Generated: {base}_json.json")
            
            # Format 3: key=value
            with open(f"{base}_kv.txt", 'w') as f:
                f.write(f"protocol=vless\n")
                f.write(f"server={args.server}\n")
                f.write(f"port={args.port}\n")
                f.write(f"uuid={args.uuid}\n")
                f.write(f"encryption=none\n")
                f.write(f"transport=ws\n")
                f.write(f"path=/\n")
                f.write(f"tls=True\n")
                f.write(f"sni={args.sni}\n")
                f.write(f"remarks={custom_remarks or 'g2ray'}\n")
            print(f"✅ Generated: {base}_kv.txt")
            
            print("\n📁 Test all these files in NPV Tunnel!")
                
    except Exception as e:
        print(f"❌ Error: {e}")
        sys.exit(1)